# This is an example configuration that loads the "Kitchen" scene from the
# local MoveIt warehouse and benchmarks the "manipulator" group over all pairs
# of motion plan queries and start states in the Kitchen scene.

# Five planners from two different plugins are run a total of 50 times each, with a
# maximum of 10 seconds per run.  Output is stored in the /tmp/moveit_benchmarks directory.

benchmark_config:
    warehouse:
        host: 127.0.0.1
        port: 33829
        scene_name: RealScene1     # Required
    parameters:
        name: RealScenePick1
        runs: 100
        group: manipulator      # Required
        timeout: 20.0
        output_directory: /home/sebi/benchmarks/
        queries: RealPick1 # .*
        start_states: RealStart1 # .*
    planning_pipelines:
        - name: ompl
          planners:
            - RRTConnect
            - RRT
            - RRTstar
            - PRM
            - PRMstar
            #- LazyPRM
            #- LazyPRMstar
        - name: chomp
          planners:
            - CHOMP
        - name: stomp
          planners:
            - STOMP
        - name: ompl_chomp
          planners:
            - RRTConnect
            - RRT
            - RRTstar
            - PRM
            - PRMstar
            #- LazyPRM
            #- LazyPRMstar
        - name: ompl_stomp
          planners:
            - RRTConnect
            - RRT
            - RRTstar
            - PRM
            - PRMstar
            #- LazyPRM
            #- LazyPRMstar
        - name: chomp_stomp
          planners:
            - CHOMP
        - name: stomp_chomp
          planners:
            - STOMP
